# Generated by Django 2.1.1 on 2018-12-21 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
                ('collected', models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v_video',
            },
        ),
    ]
