# Generated by Django 2.1.1 on 2018-12-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
