# Generated by Django 2.1.1 on 2018-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20181222_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True),
        ),
    ]
