# Generated by Django 2.1.1 on 2018-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20181223_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], default=0, max_length=1, null=True),
        ),
    ]
